{% set name = "napari-3d-counter" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d350f2561f880c708d882aaf0cd6fd77b396379dee0a2922729f6a61cbc26d1e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools >=42.0.0
    - setuptools-scm
    - wheel
  run:
    - matplotlib-base
    - napari ==0.5.4
    - numpy
    - pandas
    - python >=3.9
    - qtpy
    - scikit-image

test:
  imports:
    - napari_3d_counter
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt

about:
  home: https://pypi.org/project/napari-3d-counter
  summary: A simple plugin for counting objects in 3D images
  license: GPL-3.0-or-later
  license_file: LICENSE
  dev_url: https://github.com/pnewstein/napari-3d-counter

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - pnewstein
