{% set name = "napari-3d-counter" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3e1f8d97979b315647cd914575f4668ee2f490e4afa114db3e13ec193d1c0d59

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=42.0.0
    - setuptools-scm
    - wheel
  run:
    - matplotlib-base
    - napari <=0.4.19
    - numpy
    - pandas
    - python >=3.8
    - qtpy
    - scikit-image

test:
  imports:
    - napari_3d_counter
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt

about:
  home: https://pypi.org/project/napari-3d-counter
  summary: A simple plugin for counting objects in 3D images
  license: GPL-3.0-or-later
  license_file: LICENSE
  dev_url: https://github.com/pnewstein/napari-3d-counter

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - pnewstein
