{% set name = "napari-3d-counter" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f5512bf36cf4e5d735882e649449aef3c2da1e169a5ffd7c913838d7c3fa3221

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=42.0.0
    - setuptools-scm
    - wheel
  run:
    - napari ==0.6.2
    - numpy
    - pandas
    - python >={{ python_min }}
    - qtpy
    - scikit-image

test:
  imports:
    - napari_3d_counter
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-3d-counter
  summary: A simple plugin for counting objects in 3D images
  license: GPL-3.0-or-later
  license_file: LICENSE
  dev_url: https://github.com/pnewstein/napari-3d-counter

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - pnewstein
